# Generated by Django 4.2.8 on 2023-12-16 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimg', models.ImageField(upload_to='dimages/')),
                ('oimg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mlAPI.image')),
            ],
        ),
    ]
